# Generated by Django 4.2.5 on 2023-09-26 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc35ff62-df1b-4b18-90a3-27e835913c2c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
