# Generated by Django 4.2.5 on 2023-09-26 08:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='book',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cfc077a-df9d-411a-b61c-dcbee62ccd23'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cfc077a-df9d-411a-b61c-dcbee62ccd23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
