# Generated by Django 4.2.5 on 2023-09-26 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id_alter_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3090b5b7-07a6-4b26-b1f3-12b95bed2f74'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3090b5b7-07a6-4b26-b1f3-12b95bed2f74'), editable=False, primary_key=True, serialize=False),
        ),
    ]
