# Generated by Django 4.2.5 on 2023-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_id_alter_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='null', upload_to='books'),
        ),
    ]
