# Generated by Django 4.2.5 on 2023-09-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
