# Generated by Django 4.2.5 on 2023-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
