# Generated by Django 4.2.5 on 2023-09-26 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cfc077a-df9d-411a-b61c-dcbee62ccd23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
